version: '3.4'

services:
  logsapi:
    image: ${DOCKER_REGISTRY-}logsapi
    container_name: logs_api
    restart: always
    build:
      context: .
      dockerfile: LogsAPI/Dockerfile
    ports:
      - "8080:80"
      - "8022:22"
  app3_fredfanpage:
    image: ${DOCKER_REGISTRY-}app3fredfanpage
    container_name: fredfanpage
    build:
      context: .
      dockerfile: APP3_FredFanPage/Dockerfile
    ports:
      - "8082:80"
  watcher:
     image: claudegp/watcher-app3:latest
     container_name: watcher
     restart: always
     build:
       context: watcher
       dockerfile: Dockerfile
     logging:
       driver: "none"
     depends_on:
       - logs_api
