version: '3.4'

services:
  logsapi:
    image: ${DOCKER_REGISTRY-}logsapi
    build:
      context: .
      dockerfile: LogsAPI/Dockerfile
    ports:
        - "8080:80"
        - "8443:443"
        - "8022:22"

  app3_fredfanpage:
    image: ${DOCKER_REGISTRY-}app3fredfanpage
    container_name: fredfanpage
    build:
      context: .
      dockerfile: APP3_FredFanPage/Dockerfile
    ports:
        - "8081:80"
        - "8444:443"