version: '3.4'

services:
  logsapi:
    image: ${DOCKER_REGISTRY-}logsapi
    container_name: logs_api
    build:
      context: .
      dockerfile: LogsAPI/Dockerfile
    ports:
        - "8080:80"
        - "8443:443"
        - "8022:22"
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000 #optional
    restart: unless-stopped
  kalilinux:
    image: kali
    container_name: kalilinux
    build:
      context: .
      dockerfile: KaliLinux/Dockerfile
    stdin_open: true 
    tty: true