version: '3.4'

services:
  logsapi:
    image: ${DOCKER_REGISTRY-}logsapi
    container_name: logs_api
    restart: always
    build:
      context: .
      dockerfile: LogsAPI/Dockerfile
    ports:
      - "8080:80"
      - "8022:22"
  app3_fredfanpage:
    image: ${DOCKER_REGISTRY-}app3fredfanpage
    container_name: fredfanpage
    build:
      context: .
      dockerfile: APP3_FredFanPage/Dockerfile
    ports:
      - "8081:80"
  attacker:
    image: ${DOCKER_REGISTRY}attacker
    container_name: attacker
    restart: always
    build:
      context: attacker
      dockerfile: Dockerfile
    depends_on:
      - logs_api
